apiVersion: v1
kind: Pod
metadata:
        name: test-pod
spec:
        containers:
                - name: sample-ctr

                  imagePullPolicy: IfNotPresent
                  image: hello-world
                  ports:
                          - containerPort: 8080

        
