apiVersion: v1
kind: Service
metadata:
        name: sample-svc
spec:
        ports:
                - protocol: TCP
                  port: 80
                  targetPort: 30005
        selector:
                app: deploy2

  
