apiVersion: apps/v1
kind: Deployment
metadata:
  name: edureka-api-deployment-rollupdate
spec:
  replicas: 3
  selector:
    matchLabels:
      type: web-api
  template:
    metadata:
      name: edureka-pod
      labels:
        type: web-api
    spec:
      containers:
        - image: jenkins:latest
          imagePullPolicy: IfNotPresent
          name: edureka-api-container
          ports:
            - containerPort: 8080
